// apps/stress-test/src/wc/simple-stress/stressContainer.ts
import { FASTElement, customElement, attr, html, css, repeat } from '@microsoft/fast-element';
import { injectGlobalCss } from '../../shared/injectStyles';
import { getTestParams } from '../../shared/testParams';
import { performanceMeasure } from '../../shared/usePerformanceMeasure';

const styles = css`
  :host {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
  }
`;

// ${repeat(el => new Array(Number(el.numChildren)).fill('1'), html`<stress-component></stress-component>`)}
const template = html<StressContainer>`<slot></slot>`;

@customElement({
  name: 'stress-container',
  template,
  styles,
})
export class StressContainer extends FASTElement {
  constructor() {
    super();
  }

  public connectedCallback(): void {
    super.connectedCallback();

    if (getTestParams().test === 'mount') {
      performance.mark('start');
    }

    const slot = this.shadowRoot?.querySelector('slot');
    slot?.addEventListener(
      'slotchange',
      e => {
        if (getTestParams().test === 'inject-styles') {
          setTimeout(() => {
            performanceMeasure('stress', 'start');
            injectGlobalCss();
          }, 2000);
          return;
        }

        if (getTestParams().test === 'mount') {
          // requestPostAnimationFrame polyfill
          requestAnimationFrame(() => {
            addEventListener(
              'message',
              () => {
                performance.measure('stress', 'start');
              },
              { once: true },
            );
            postMessage('', '*');
          });
        }
      },
      { once: true },
    );
  }
}

// apps/stress-test/src/v9/simple-stress/StressContainer.tsx
import { makeStyles, shorthands } from '@fluentui/react-components';
import * as React from 'react';
import { injectGlobalCss } from '../../shared/injectStyles';
import { getTestParams } from '../../shared/testParams';
import { performanceMeasure, usePerformanceMeasure } from '../../shared/usePerformanceMeasure';
import { StressComponent } from './StressComponent';

const useStyles = makeStyles({
  container: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    ...shorthands.gap('10px'),
  },
});

export type StressContainerProps = {
  numChildren?: number;
};

export const StressContainer: React.FC<StressContainerProps> = ({ numChildren = 10 }) => {
  if (getTestParams().test === 'mount') {
    performanceMeasure('stress', 'start');
  } else if (getTestParams().test === 'inject-styles') {
    setTimeout(() => {
      performanceMeasure('stress', 'start');
      injectGlobalCss();
    }, 2000);
  }

  const styles = useStyles();

  const kids = new Array(numChildren).fill('1');
  return (
    <div className={styles.container}>
      {kids.map((_, index) => {
        return <StressComponent />;
      })}
    </div>
  );
};
